#![allow(unused_imports, unused_attributes, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod r#i_network;
pub mod r#i_network_middleware_service;
pub mod r#i_network_registry;
pub mod r#i_network_restake_delegator;
pub mod r#i_set_max_network_limit_hook;
